<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cars', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->string('sellerphoneno')->nullable();
            $table->unsignedBigInteger('sellertypeid')->nullable();
            $table->text('images')->nullable();
            $table->string('first_name')->nullable();
            $table->string('last_name')->nullable();
            $table->date('date')->nullable();
            $table->time('time')->nullable();
            $table->string('carmake')->nullable();
            $table->string('carmodel')->nullable();
            $table->year('year')->nullable();
            $table->string('vehicleenginesize')->nullable();
            $table->string('vehicleregionalspec')->nullable();
            $table->unsignedInteger('mileage')->nullable();
            $table->string('vehicletransmission')->nullable();
            $table->string('fueltype')->nullable();
            $table->string('vehicleinterior')->nullable();
            $table->string('vinnumber')->nullable();
            $table->boolean('vehicleapretire')->nullable();
            $table->string('engine_upper_cover')->nullable();
            $table->text('engine_upper_cover_img')->nullable();
            $table->string('engine_shield_cover')->nullable();
            $table->text('engine_shield_cover_img')->nullable();
            $table->string('engine_mounts')->nullable();
            $table->text('engine_mounts_img')->nullable();
            $table->string('bonnet_hinge_holder')->nullable();
            $table->text('bonnet_hinge_holder_img')->nullable();
            $table->string('turbo_supercharger')->nullable();
            $table->text('turbo_supercharger_img')->nullable();
            $table->string('fender_liners')->nullable();
            $table->text('fender_liners_img')->nullable();
            $table->string('drive_belt_pulleys')->nullable();
            $table->text('drive_belt_pulleys_img')->nullable();
            $table->string('engine_idle')->nullable();
            $table->string('engine_oil_filler_cap')->nullable();
            $table->text('engine_oil_filler_cap_img')->nullable();
            $table->string('radiator')->nullable();
            $table->text('radiator_img')->nullable();
            $table->string('engine_oil_leaks')->nullable();
            $table->text('engine_oil_leaks_img')->nullable();
            $table->string('engine_oil_condition')->nullable();
            $table->text('engine_oil_condition_img')->nullable();
            $table->string('coolant_condition')->nullable();
            $table->text('coolant_condition_img')->nullable();
            $table->string('coolant_cap')->nullable();
            $table->text('coolant_cap_img')->nullable();
            $table->string('hoses_pipes')->nullable();
            $table->text('hoses_pipes_img')->nullable();
            $table->string('exhaust_system')->nullable();
            $table->text('exhaust_system_img')->nullable();
            $table->string('visible_rust')->nullable();
            $table->text('visible_rust_img')->nullable();
            $table->string('battery_condition')->nullable();
            $table->string('fluid_level_&_condition')->nullable();
            $table->string('fluid_level_img')->nullable();
            $table->string('transmission_fluid_leaks')->nullable();
            $table->text('transmission_fluid_leaks_img')->nullable();
            $table->string('gear_Selector')->nullable();
            $table->text('gear_selector_img')->nullable();
            $table->string('noise')->nullable();
            $table->string('gear_shifting')->nullable();
            $table->string('brake_pads_front')->nullable();
            $table->string('brake_pads_rear')->nullable();
            $table->string('brake_disc_front')->nullable();
            $table->string('brake_disc_rear')->nullable();
            $table->string('abs_sensors')->nullable();
            $table->string('handbrake')->nullable();
            $table->string('front_suspension')->nullable();
            $table->text('front_suspension_img')->nullable();
            $table->string('rear_suspension')->nullable();
            $table->text('rear_suspension_img')->nullable();
            $table->text('front_left_tyre_img')->nullable();
            $table->text('rear_left_tyre_img')->nullable();
            $table->text('rear_right_tyre_img')->nullable();
            $table->text('front_right_tyre_img')->nullable();
            $table->string('key_remote')->nullable();
            $table->text('key_remote_img')->nullable();
            $table->string('entertainment_system')->nullable();
            $table->text('entertainment_system_img')->nullable();
            $table->string('windows_operation')->nullable();
            $table->text('window_operations_img')->nullable();
            $table->string('seats_adjustment')->nullable();
            $table->text('seats_adjustment_img')->nullable();
            $table->string('door_lock_unlock')->nullable();
            $table->text('door_lock_unlock_img')->nullable();
            $table->string('ac_control_cooling')->nullable();
            $table->text('ac_control_cooling_img')->nullable();
            $table->text('center_console_buttons_img')->nullable();
            $table->string('cameras')->nullable();
            $table->text('cameras_img')->nullable();
            $table->string('gauges')->nullable();
            $table->text('guages_img')->nullable();
            $table->string('rear_view_side_mirror_elec')->nullable();
            $table->text('rear_view_side_mirror_elec_img')->nullable();
            $table->string('ac_grilles')->nullable();
            $table->text('ac_grilles_img')->nullable();
            $table->string('starting_ignition_system')->nullable();
            $table->text('starting_ignition_system_img')->nullable();
            $table->string('brake_lights')->nullable();
            $table->text('brake_lights_fault_img')->nullable();
            $table->string('headlights')->nullable();
            $table->text('headlights_img')->nullable();
            $table->string('fog_lights')->nullable();
            $table->text('fog_lights_img')->nullable();
            $table->string('reverse_lights')->nullable();
            // $table->text('reverse_lights_img')->nullable();
            // $table->string('high_beams')->nullable();
            // $table->text('high_beams_img')->nullable();
            // $table->string('no_of_plate_lights')->nullable();
            // $table->text('no_of_plate_lights_img')->nullable();
            // $table->string('indicators_hazards')->nullable();
            // $table->text('indicators_hazards_img')->nullable();
            // $table->string('wipers')->nullable();
            // $table->text('wipers_img')->nullable();
            // $table->string('soft_closing_door')->nullable();
            // $table->text('soft_closing_door_img')->nullable();
            // $table->string('sunroof_moonroof')->nullable();
            // $table->text('sunroof_moonroof_img')->nullable();
            // $table->string('interior_lights')->nullable();
            // $table->text('interior_lights_img')->nullable();
            // $table->string('cruise_control')->nullable();
            // $table->text('cruise_control_img')->nullable();
            // $table->string('horn')->nullable();
            // $table->string('parking_sensor_fault')->nullable();
            // $table->string('roof_lining')->nullable();
            // $table->text('roof_lining_img')->nullable();
            // $table->string('rear_view_mirror')->nullable();
            // $table->text('rear_view_mirror_img')->nullable();
            // $table->string('steering_wheel_upholstery')->nullable();
            // $table->text('steering_wheel_upholstery_img')->nullable();
            // $table->string('seats_upholstery')->nullable();
            // $table->text('seats_upholstery_img')->nullable();
            // $table->string('gear_liver')->nullable();
            // $table->text('gear_liver_img')->nullable();
            // $table->string('trunk_lining')->nullable();
            // $table->text('trunk_lining_img')->nullable();
            // $table->string('armest_side_pockets')->nullable();
            // $table->text('armest_side_pockets_img')->nullable();
            // $table->string('dashboard')->nullable();
            // $table->text('dashboard_img')->nullable();
            // $table->string('floor_mats')->nullable();
            // $table->text('floor_mats_img')->nullable();
            // $table->string('doors')->nullable();
            // $table->text('doors_img')->nullable();
            // $table->string('front_windscreen')->nullable();
            // $table->text('front_windscreen_img')->nullable();
            // $table->string('rear_windscreen')->nullable();
            // $table->text('rear_windscreen_img')->nullable();
            // $table->text('exterior_img')->nullable();
            // $table->text('interior_img')->nullable();
            // $table->text('engine_undercarriage_img')->nullable();
            // $table->text('vehicle_diagnostic_img')->nullable();
            // $table->string('cv_frunk_condition')->nullable();
            // $table->text('cv_frunk_condition_img')->nullable();
            // $table->string('cv_undercarriage_shield_cover')->nullable();
            // $table->text('cv_undercarriage_shield_cover_img')->nullable();
            // $table->string('cv_bonnet_hinge_holder')->nullable();
            // $table->text('cv_bonnet_hinge_holder_img')->nullable();
            // $table->string('cv_fender_liners')->nullable();
            // $table->text('cv_fender_liners_img')->nullable();
            // $table->string('cv_radiator')->nullable();
            // $table->text('cv_radiator_img')->nullable();
            // $table->string('cv_coolant_condition')->nullable();
            // $table->text('cv_coolant_condition_img')->nullable();
            // $table->string('cv_coolant_Cap')->nullable();
            // $table->text('cv_coolant_img')->nullable();
            // $table->string('cv_hoses_pipes')->nullable();
            // $table->string('cv_hoses_damage')->nullable();
            // $table->string('cv_visible_rust')->nullable();
            // $table->text('cv_visible_rust_img')->nullable();
            // $table->string('battery_health')->nullable();
            // $table->string('charging_port')->nullable();
            // $table->text('charging_port_img')->nullable();
            // $table->string('charging_feature')->nullable();
            // $table->text('charging_feature_img')->nullable();
            // $table->string('electric_motor')->nullable();
            // $table->text('electric_motor_img')->nullable();
            // $table->text('frunk_trunk_img')->nullable();
            // $table->string('vehicle_summary')->nullable();
            // $table->string('signature')->nullable();
            $table->tinyInteger('status')->default(1);
            $table->foreign('user_id')->references('id')->on('users');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cars');
    }
};
